language: java
jdk:
  - oraclejdk8
sudo: false
script:
  - echo $CI_DEPLOY_SERVER
  - echo $CI_DEPLOY_CONTEXT
  - mvn clean verify
  - chmod ugo+x ./deploy.sh
  - eval 'curl -u "$CI_DEPLOY_USERNAME:$CI_DEPLOY_PASSWORD" --upload-file ./target/pom-checker*.war "$CI_DEPLOY_SERVER/manager/text/deploy?path=/$CI_DEPLOY_CONTEXT&update=true"'
  - ./deploy.sh
