language: java
jdk:
  - oraclejdk8
sudo: false
script:
  - mvn clean verify
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "./target/pom-checker-$TRAVIS_TAG.war"
  skip_cleanup: true
  on:
    branch: master
    tags: true