language: java
jdk:
  - oraclejdk8
sudo: false
script: mvn clean verify
script: curl -u "$ciDeployUsername:$ciDeployPassword" --upload-file ./target/pom-checker*.war "$ciDeployServer/manager/text/deploy?path=/$ciDeployContext&update=true"